import React from 'react';

export const PrivacyPolicy: React.FC = () => (
  <div className="space-y-6 text-sm md:text-base leading-relaxed text-foreground/90">
    <h1 className="text-3xl font-bold tracking-tight border-b pb-4">Privacy Policy</h1>
    <p className="text-muted-foreground italic">Last Updated: March 7, 2026</p>
    
    <section className="space-y-3">
      <h2 className="text-xl font-semibold">1. Introduction</h2>
      <p>
        Welcome to kinich ("we," "our," or "us"). We respect your privacy and are committed to protecting your personal data. This Privacy Policy explains how we handle information when you use our application.
      </p>
    </section>

    <section className="space-y-3">
      <h2 className="text-xl font-semibold">2. Data We Collect</h2>
      <p>
        <strong>Personal Data:</strong> We do not require user accounts or collect personally identifiable information (PII) such as names, email addresses, or phone numbers directly, unless you voluntarily provide them through support channels.
      </p>
      <p>
        <strong>Usage Data:</strong> We may collect anonymous data about how you interact with the app (e.g., search terms, features used) to improve the service.
      </p>
      <p>
        <strong>Local Storage:</strong> We use browser local storage to save your preferences, such as theme settings and chat memory, locally on your device.
      </p>
    </section>

    <section className="space-y-3">
      <h2 className="text-xl font-semibold">3. Third-Party Services (AI Processing)</h2>
      <p>
        Our application utilizes the <strong>Google Gemini API</strong> to generate content, summaries, and chat responses. 
      </p>
      <ul className="list-disc pl-6 space-y-2">
        <li>When you enter a prompt or search term, that data is sent to Google's servers for processing.</li>
        <li>Google handles this data according to their own privacy policies. We recommend reviewing the <a href="https://ai.google.dev/terms" target="_blank" rel="noopener noreferrer" className="text-primary underline">Google AI Terms of Service</a>.</li>
        <li>Do not enter sensitive, private, or confidential information into the application.</li>
      </ul>
    </section>

    <section className="space-y-3">
      <h2 className="text-xl font-semibold">4. Data Security</h2>
      <p>
        We implement reasonable security measures to protect the information processed through our app. However, no method of transmission over the internet is 100% secure.
      </p>
    </section>

    <section className="space-y-3">
      <h2 className="text-xl font-semibold">5. Your Rights</h2>
      <p>
        Depending on your location (e.g., GDPR in Europe), you may have rights regarding your data, including the right to access, correct, or delete any data we might hold. Since we store most data locally, you can clear your browser cache/local storage to delete your preferences.
      </p>
    </section>

    <section className="space-y-3">
      <h2 className="text-xl font-semibold">6. Changes to This Policy</h2>
      <p>
        We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
      </p>
    </section>
  </div>
);

export const TermsOfService: React.FC = () => (
  <div className="space-y-6 text-sm md:text-base leading-relaxed text-foreground/90">
    <h1 className="text-3xl font-bold tracking-tight border-b pb-4">Terms of Service</h1>
    <p className="text-muted-foreground italic">Last Updated: March 7, 2026</p>

    <section className="space-y-3">
      <h2 className="text-xl font-semibold">1. Acceptance of Terms</h2>
      <p>
        By accessing or using kinich, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the application.
      </p>
    </section>

    <section className="space-y-3">
      <h2 className="text-xl font-semibold">2. Description of Service</h2>
      <p>
        kinich is an AI-powered educational tool that provides summaries, mind maps, quizzes, and interactive learning experiences based on academic topics and research data.
      </p>
    </section>

    <section className="space-y-3">
      <h2 className="text-xl font-semibold">3. AI Content Disclaimer</h2>
      <div className="p-4 bg-destructive/10 border-l-4 border-destructive rounded">
        <p className="font-bold text-destructive">IMPORTANT NOTICE:</p>
        <p>
          Content provided by this application is generated by Artificial Intelligence (Google Gemini). AI can hallucinate, provide inaccurate information, or reflect biases. 
          <strong> All content should be verified against primary sources.</strong> We are not responsible for any actions taken based on AI-generated content.
        </p>
      </div>
    </section>

    <section className="space-y-3">
      <h2 className="text-xl font-semibold">4. Intellectual Property</h2>
      <p>
        The application interface, design, and original code are the property of the developers. Academic papers and data retrieved from external repositories are subject to the original authors' licenses and the source repository's terms of use.
      </p>
    </section>

    <section className="space-y-3">
      <h2 className="text-xl font-semibold">5. Prohibited Use</h2>
      <p>You agree not to use the service to:</p>
      <ul className="list-disc pl-6 space-y-2">
        <li>Generate harmful, illegal, or offensive content.</li>
        <li>Attempt to reverse-engineer or disrupt the application infrastructure.</li>
        <li>Violate any applicable local, state, or international laws.</li>
      </ul>
    </section>

    <section className="space-y-3">
      <h2 className="text-xl font-semibold">6. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, kinich and its developers shall not be liable for any indirect, incidental, special, or consequential damages resulting from the use or inability to use the service.
      </p>
    </section>

    <section className="space-y-3">
      <h2 className="text-xl font-semibold">7. Governing Law</h2>
      <p>
        These terms shall be governed by and construed in accordance with the laws of the jurisdiction in which the developer operates, without regard to its conflict of law provisions.
      </p>
    </section>
  </div>
);
